# Generated by Django 2.0.2 on 2020-01-24 15:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('reviews_total', models.FloatField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('pub_date', models.DateTimeField(null=True)),
                ('interest', models.CharField(max_length=500, null=True)),
                ('interest_rating', models.IntegerField(null=True)),
                ('brevity', models.CharField(max_length=500, null=True)),
                ('brevity_rating', models.IntegerField(null=True)),
                ('not_good', models.CharField(max_length=500, null=True)),
                ('general_comments', models.CharField(max_length=500, null=True)),
                ('avg_rating', models.FloatField(null=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='content.Content')),
            ],
        ),
    ]
