# Generated by Django 2.0.2 on 2020-01-25 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='clarity',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='clarity_rating',
            field=models.IntegerField(null=True),
        ),
    ]
