# Generated by Django 2.0.2 on 2020-01-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_auto_20200125_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
