# Generated by Django 2.0.2 on 2020-01-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_auto_20200127_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='not_good',
        ),
    ]
