# Generated by Django 2.0.2 on 2020-02-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_auto_20200130_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
