# Generated by Django 2.0.2 on 2019-11-25 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_content_reviews_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='content.Content'),
            preserve_default=False,
        ),
    ]
