# Generated by Django 2.0.2 on 2019-11-25 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_review_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
    ]
