# Generated by Django 2.0.2 on 2019-12-05 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0018_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='avg',
            field=models.IntegerField(null=True),
        ),
    ]
