# Generated by Django 2.0.2 on 2019-12-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0019_review_avg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='avg',
            new_name='avg_rating',
        ),
    ]
