# Generated by Django 2.0.2 on 2019-12-07 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0020_auto_20191207_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='reviews_total',
        ),
    ]
