# Generated by Django 2.0.2 on 2019-12-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0021_remove_content_reviews_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='reviews_total',
            field=models.IntegerField(null=True),
        ),
    ]
