# Generated by Django 2.0.2 on 2019-12-08 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0022_content_reviews_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='reviews_total',
            field=models.FloatField(null=True),
        ),
    ]
