# Generated by Django 2.0.2 on 2019-12-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0024_auto_20191217_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='avg_rating',
        ),
    ]
