# Generated by Django 2.0.2 on 2019-12-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0026_review_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='actionability',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='actionability_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='general_comments',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='readability',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='readability_rating',
            field=models.IntegerField(null=True),
        ),
    ]
