# Generated by Django 2.0.2 on 2019-12-19 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0027_auto_20191219_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='readability_rating',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
