# Generated by Django 2.0.2 on 2019-12-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0028_auto_20191219_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='readability_rating',
            field=models.IntegerField(null=True),
        ),
    ]
