# Generated by Django 2.0.2 on 2020-01-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0030_content_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
