# Generated by Django 2.0.2 on 2020-01-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0031_review_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='reviewer',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
