# Generated by Django 2.0.2 on 2020-01-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0032_auto_20200109_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(null=True),
        ),
    ]
