# Generated by Django 2.0.2 on 2020-01-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0033_review_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='pub_date',
            field=models.DateTimeField(default=30, verbose_name='date published'),
            preserve_default=False,
        ),
    ]
