# Generated by Django 2.0.2 on 2020-01-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0034_auto_20200109_1215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pub_date',
        ),
    ]
